name: Release vue-quill-next

on:
  workflow_dispatch:
  push:
    branches:
      - alpha
      - beta
      - master
    paths:
      - 'packages/vue-quill-next/**'
jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install root deps
        run: npm ci
      - name: Install package deps
        working-directory: packages/vue-quill-next
        run: npm ci
      - name: Release package
        working-directory: packages/vue-quill-next
        run: npx ts-node ../../scripts/release.ts vue-quill-next
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}